# config.yml
input:
  ensemble_pattern: "data/total_precipitation_2017*.nc"
  reference_file: "data/INCA_RR_20171*.nc"
subset:
  lat_bounds: [46, 48]
  lon_bounds: [11, 13]
  start_time: "2017-10-01T00:00:00"
  end_time: "2017-10-02T23:00:00"
output:
  save_netcdf: "output/bias_metrics.nc"
  save_plot: "output/rmse_map_new.png"
